apiVersion: v1
kind: Secret
metadata:
  name: books-db-secret
type: Opaque
stringData:
  POSTGRES_USER: books
  POSTGRES_PASSWORD: secret
  POSTGRES_DB: books
  POSTGRES_HOST: books-db-service
  POSTGRES_PORT: "5432"
