apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordinator-api
  template:
    metadata:
      labels:
        app: coordinator-api
    spec:
      containers:
      - name: coordinator-api
        image: misha654/purchase-coordinator-api:latest
        workingDir: /app/coordinator
        command:
          - uvicorn
          - coordinator.main:app
          - --host
          - "0.0.0.0"
          - --port
          - "8000"
        envFrom:
          - secretRef:
              name: coordinator-secret
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
