apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-api
  template:
    metadata:
      labels:
        app: users-api
    spec:
      initContainers:
        - name: run-migrations
          image: misha654/purchase-users-api:latest
          workingDir: /app/user-service
          command:
            - sh
            - -c
            - |
              until pg_isready -h users-db-service -U users; do
                echo "Waiting for db..."
                sleep 1
              done
              alembic upgrade head
          envFrom:
            - secretRef:
                name: users-db-secret
      containers:
      - name: users-api
        image: misha654/purchase-users-api:latest
        workingDir: /app/user-service
        command:
          - uvicorn
          - user_service.main:app
          - --host
          - "0.0.0.0"
          - --port
          - "8000"
        envFrom:
          - secretRef:
              name: users-db-secret
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
