apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-postgres
  template:
    metadata:
      labels:
        app: users-postgres
    spec:
      containers:
      - name: users-postgres
        image: postgres:16
        args:
          - postgres
          - -c
          - max_prepared_transactions=1000
        envFrom:
          - secretRef:
              name: users-db-secret
        ports:
          - containerPort: 5432
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres"]
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: users-postgres-pvc
